import localFont from "next/font/local";
import AppProvider from "./components/AppContext"
import "./globals.css";
import Head from 'next/head';
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Header1 from "./components/Header1";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet"/>
      <link
  href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css"
  rel="stylesheet"
/>

      </Head>
   
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <AppProvider>
        {/* <Header1 /> */}
        {children}
        </AppProvider>
        </div>
        <script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-3k8kbe6c6hB6E2YxN+T9PfzN+EGHICIkTc7AW/5mB0Gz4lDQj3hk8wQokZp8g5kK"
  crossorigin="anonymous"
></script>

      </body>
    </html>
  );
}
